/**
 * This file was auto-generated by scripts/codegen.py.
 * Do not make direct changes to the file.
 */

import { appRequest } from "@/api/apps";
import type {
  BudgetOverviewWidgetData,
  ConfigFieldSchema,
  FinanceActionResponse,
  FinanceBudgetCategoryStatus,
  FinanceBudgetOverviewResponse,
  FinanceCategoryBreakdownResponse,
  FinanceCategoryRead,
  FinanceCreateCategoryRequest,
  FinanceCreateTransactionRequest,
  FinanceCreateWalletRequest,
  FinanceMonthlyTrendResponse,
  FinanceSummaryResponse,
  FinanceTransactionRead,
  FinanceTransferRequest,
  FinanceTransferResponse,
  FinanceUpdateCategoryRequest,
  FinanceUpdateTransactionRequest,
  FinanceUpdateWalletRequest,
  FinanceWalletRead,
  PreferenceUpdate,
  RecentTransactionsWidgetData,
  TotalBalanceWidgetData,
  WidgetDataConfigSchema,
  WidgetDataConfigUpdate,
  WidgetManifestSchema,
  WidgetPreferenceSchema,
} from "@/types/generated";

export type ActionResponse = FinanceActionResponse;
export type BudgetCategoryStatus = FinanceBudgetCategoryStatus;
export type BudgetOverviewResponse = FinanceBudgetOverviewResponse;
export type CategoryBreakdownResponse = FinanceCategoryBreakdownResponse;
export type CategoryRead = FinanceCategoryRead;
export type CreateCategoryRequest = FinanceCreateCategoryRequest;
export type CreateTransactionRequest = FinanceCreateTransactionRequest;
export type CreateWalletRequest = FinanceCreateWalletRequest;
export type MonthlyTrendResponse = FinanceMonthlyTrendResponse;
export type SummaryResponse = FinanceSummaryResponse;
export type TransactionRead = FinanceTransactionRead;
export type TransferRequest = FinanceTransferRequest;
export type TransferResponse = FinanceTransferResponse;
export type UpdateCategoryRequest = FinanceUpdateCategoryRequest;
export type UpdateTransactionRequest = FinanceUpdateTransactionRequest;
export type UpdateWalletRequest = FinanceUpdateWalletRequest;
export type WalletRead = FinanceWalletRead;

export type CheckBudgetResponse = BudgetCategoryStatus | BudgetOverviewResponse;
export type GetCategoriesResponse = CategoryRead[];
export type GetPreferencesResponse = WidgetPreferenceSchema[];
export type UpdatePreferencesResponse = WidgetPreferenceSchema[];
export type GetTransactionsResponse = TransactionRead[];
export type SearchTransactionsResponse = TransactionRead[];
export type GetWalletsResponse = WalletRead[];
export type GetWidgetsResponse = WidgetManifestSchema[];
export type GetWidgetDataResponse = TotalBalanceWidgetData | BudgetOverviewWidgetData | RecentTransactionsWidgetData;
export type GetWidgetOptionsResponse = ConfigFieldSchema[];

export interface GetCategoryBreakdownParams {
  month?: number | null;
  year?: number | null;
}

export interface GetMonthlyTrendParams {
  months?: number;
}

export interface CheckBudgetParams {
  category_id?: string | null;
}

export interface GetTransactionsParams {
  type?: string | null;
  category_id?: string | null;
  wallet_id?: string | null;
  skip?: number;
  limit?: number;
}

export interface SearchTransactionsParams {
  query?: string | null;
  start_date?: string | null;
  end_date?: string | null;
  limit?: number;
}

export async function getCategoryBreakdown(params: GetCategoryBreakdownParams = {}): Promise<CategoryBreakdownResponse> {
  const query = new URLSearchParams();
  if (params.month !== undefined && params.month !== null) {
    query.set("month", String(params.month));
  }
  if (params.year !== undefined && params.year !== null) {
    query.set("year", String(params.year));
  }
  const suffix = query.toString();
  return appRequest<CategoryBreakdownResponse>("finance", `/analytics/category-breakdown${suffix ? `?${suffix}` : ""}`);
}

export async function getMonthlyTrend(params: GetMonthlyTrendParams = {}): Promise<MonthlyTrendResponse> {
  const query = new URLSearchParams();
  if (params.months !== undefined && params.months !== null) {
    query.set("months", String(params.months));
  }
  const suffix = query.toString();
  return appRequest<MonthlyTrendResponse>("finance", `/analytics/monthly-trend${suffix ? `?${suffix}` : ""}`);
}

export async function checkBudget(params: CheckBudgetParams = {}): Promise<CheckBudgetResponse> {
  const query = new URLSearchParams();
  if (params.category_id !== undefined && params.category_id !== null) {
    query.set("category_id", String(params.category_id));
  }
  const suffix = query.toString();
  return appRequest<CheckBudgetResponse>("finance", `/budget/check${suffix ? `?${suffix}` : ""}`);
}

export async function getCategories(): Promise<GetCategoriesResponse> {
  return appRequest<GetCategoriesResponse>("finance", `/categories`);
}

export async function createCategory(request: CreateCategoryRequest): Promise<CategoryRead> {
  return appRequest<CategoryRead>("finance", `/categories`, { method: "POST", body: request });
}

export async function deleteCategory(category_id: string): Promise<ActionResponse> {
  return appRequest<ActionResponse>("finance", `/categories/${encodeURIComponent(String(category_id))}`, { method: "DELETE" });
}

export async function getCategory(category_id: string): Promise<CategoryRead> {
  return appRequest<CategoryRead>("finance", `/categories/${encodeURIComponent(String(category_id))}`);
}

export async function updateCategory(category_id: string, request: UpdateCategoryRequest): Promise<CategoryRead> {
  return appRequest<CategoryRead>("finance", `/categories/${encodeURIComponent(String(category_id))}`, { method: "PATCH", body: request });
}

export async function getPreferences(): Promise<GetPreferencesResponse> {
  return appRequest<GetPreferencesResponse>("finance", `/preferences`);
}

export async function updatePreferences(request: PreferenceUpdate[]): Promise<UpdatePreferencesResponse> {
  return appRequest<UpdatePreferencesResponse>("finance", `/preferences`, { method: "PUT", body: request });
}

export async function getSummary(): Promise<SummaryResponse> {
  return appRequest<SummaryResponse>("finance", `/summary`);
}

export async function getTransactions(params: GetTransactionsParams = {}): Promise<GetTransactionsResponse> {
  const query = new URLSearchParams();
  if (params.type !== undefined && params.type !== null) {
    query.set("type", String(params.type));
  }
  if (params.category_id !== undefined && params.category_id !== null) {
    query.set("category_id", String(params.category_id));
  }
  if (params.wallet_id !== undefined && params.wallet_id !== null) {
    query.set("wallet_id", String(params.wallet_id));
  }
  if (params.skip !== undefined && params.skip !== null) {
    query.set("skip", String(params.skip));
  }
  if (params.limit !== undefined && params.limit !== null) {
    query.set("limit", String(params.limit));
  }
  const suffix = query.toString();
  return appRequest<GetTransactionsResponse>("finance", `/transactions${suffix ? `?${suffix}` : ""}`);
}

export async function createTransaction(request: CreateTransactionRequest): Promise<TransactionRead> {
  return appRequest<TransactionRead>("finance", `/transactions`, { method: "POST", body: request });
}

export async function searchTransactions(params: SearchTransactionsParams = {}): Promise<SearchTransactionsResponse> {
  const query = new URLSearchParams();
  if (params.query !== undefined && params.query !== null) {
    query.set("query", String(params.query));
  }
  if (params.start_date !== undefined && params.start_date !== null) {
    query.set("start_date", String(params.start_date));
  }
  if (params.end_date !== undefined && params.end_date !== null) {
    query.set("end_date", String(params.end_date));
  }
  if (params.limit !== undefined && params.limit !== null) {
    query.set("limit", String(params.limit));
  }
  const suffix = query.toString();
  return appRequest<SearchTransactionsResponse>("finance", `/transactions/search${suffix ? `?${suffix}` : ""}`);
}

export async function deleteTransaction(transaction_id: string): Promise<ActionResponse> {
  return appRequest<ActionResponse>("finance", `/transactions/${encodeURIComponent(String(transaction_id))}`, { method: "DELETE" });
}

export async function getTransaction(transaction_id: string): Promise<TransactionRead> {
  return appRequest<TransactionRead>("finance", `/transactions/${encodeURIComponent(String(transaction_id))}`);
}

export async function updateTransaction(transaction_id: string, request: UpdateTransactionRequest): Promise<TransactionRead> {
  return appRequest<TransactionRead>("finance", `/transactions/${encodeURIComponent(String(transaction_id))}`, { method: "PATCH", body: request });
}

export async function transfer(request: TransferRequest): Promise<TransferResponse> {
  return appRequest<TransferResponse>("finance", `/transfer`, { method: "POST", body: request });
}

export async function getWallets(): Promise<GetWalletsResponse> {
  return appRequest<GetWalletsResponse>("finance", `/wallets`);
}

export async function createWallet(request: CreateWalletRequest): Promise<WalletRead> {
  return appRequest<WalletRead>("finance", `/wallets`, { method: "POST", body: request });
}

export async function deleteWallet(wallet_id: string): Promise<ActionResponse> {
  return appRequest<ActionResponse>("finance", `/wallets/${encodeURIComponent(String(wallet_id))}`, { method: "DELETE" });
}

export async function getWallet(wallet_id: string): Promise<WalletRead> {
  return appRequest<WalletRead>("finance", `/wallets/${encodeURIComponent(String(wallet_id))}`);
}

export async function updateWallet(wallet_id: string, request: UpdateWalletRequest): Promise<WalletRead> {
  return appRequest<WalletRead>("finance", `/wallets/${encodeURIComponent(String(wallet_id))}`, { method: "PATCH", body: request });
}

export async function getWidgets(): Promise<GetWidgetsResponse> {
  return appRequest<GetWidgetsResponse>("finance", `/widgets`);
}

export async function getWidgetData(widget_id: string): Promise<GetWidgetDataResponse> {
  return appRequest<GetWidgetDataResponse>("finance", `/widgets/${encodeURIComponent(String(widget_id))}`);
}

export async function updateWidgetConfig(widget_id: string, request: WidgetDataConfigUpdate): Promise<WidgetDataConfigSchema> {
  return appRequest<WidgetDataConfigSchema>("finance", `/widgets/${encodeURIComponent(String(widget_id))}/config`, { method: "PUT", body: request });
}

export async function getWidgetOptions(widget_id: string): Promise<GetWidgetOptionsResponse> {
  return appRequest<GetWidgetOptionsResponse>("finance", `/widgets/${encodeURIComponent(String(widget_id))}/options`);
}
