/**
 * This file was auto-generated by scripts/codegen.py.
 * Do not make direct changes to the file.
 */

import type { ComponentType } from "react";

import { createDashboardWidgetRenderer } from "@/lib/dashboard-widget-renderer";

import type { DashboardWidgetRendererProps } from "./types";
import TotalBalanceWidget from "./widgets/TotalBalanceWidget";
import BudgetOverviewWidget from "./widgets/BudgetOverviewWidget";
import RecentTransactionsWidget from "./widgets/RecentTransactionsWidget";

const WIDGET_COMPONENTS = {
  "finance.total-balance": TotalBalanceWidget,
  "finance.budget-overview": BudgetOverviewWidget,
  "finance.recent-transactions": RecentTransactionsWidget,
} as const satisfies Record<string, ComponentType<DashboardWidgetRendererProps>>;

const FinanceDashboardWidget = createDashboardWidgetRenderer(WIDGET_COMPONENTS);

export default FinanceDashboardWidget;
