/**
 * This file was auto-generated by scripts/codegen.py.
 * Do not make direct changes to the file.
 */

import { appRequest } from "@/api/apps";
import type {
  CalendarActionResponse,
  CalendarCalendarRead,
  CalendarCreateCalendarRequest,
  CalendarCreateEventRequest,
  CalendarCreateRecurringRuleRequest,
  CalendarEventRead,
  CalendarRecurringRuleRead,
  CalendarScheduleTaskRequest,
  CalendarUpdateCalendarRequest,
  CalendarUpdateEventRequest,
  PreferenceUpdate,
  WidgetManifestSchema,
  WidgetPreferenceSchema,
} from "@/types/generated";

export type ActionResponse = CalendarActionResponse;
export type CalendarRead = CalendarCalendarRead;
export type CreateCalendarRequest = CalendarCreateCalendarRequest;
export type CreateEventRequest = CalendarCreateEventRequest;
export type CreateRecurringRuleRequest = CalendarCreateRecurringRuleRequest;
export type EventRead = CalendarEventRead;
export type RecurringRuleRead = CalendarRecurringRuleRead;
export type ScheduleTaskRequest = CalendarScheduleTaskRequest;
export type UpdateCalendarRequest = CalendarUpdateCalendarRequest;
export type UpdateEventRequest = CalendarUpdateEventRequest;

export type ListCalendarsResponse = CalendarRead[];
export type CheckConflictsResponse = EventRead[];
export type ListEventsResponse = EventRead[];
export type SearchEventsResponse = EventRead[];
export type GetPreferencesResponse = WidgetPreferenceSchema[];
export type UpdatePreferencesResponse = WidgetPreferenceSchema[];
export type ListRecurringRulesResponse = RecurringRuleRead[];
export type ListWidgetsResponse = WidgetManifestSchema[];

export interface CheckConflictsParams {
  start: string;
  end: string;
  exclude_event_id?: string | null;
}

export interface ListEventsParams {
  start?: string | null;
  end?: string | null;
  calendar_id?: string | null;
  limit?: number;
}

export interface SearchEventsParams {
  q: string;
  limit?: number;
}

export async function listCalendars(): Promise<ListCalendarsResponse> {
  return appRequest<ListCalendarsResponse>("calendar", `/calendars`);
}

export async function createCalendar(request: CreateCalendarRequest): Promise<CalendarRead> {
  return appRequest<CalendarRead>("calendar", `/calendars`, { method: "POST", body: request });
}

export async function deleteCalendar(calendar_id: string): Promise<ActionResponse> {
  return appRequest<ActionResponse>("calendar", `/calendars/${encodeURIComponent(String(calendar_id))}`, { method: "DELETE" });
}

export async function updateCalendar(calendar_id: string, request: UpdateCalendarRequest): Promise<CalendarRead> {
  return appRequest<CalendarRead>("calendar", `/calendars/${encodeURIComponent(String(calendar_id))}`, { method: "PATCH", body: request });
}

export async function checkConflicts(params: CheckConflictsParams): Promise<CheckConflictsResponse> {
  const query = new URLSearchParams();
  if (params.start !== undefined && params.start !== null) {
    query.set("start", String(params.start));
  }
  if (params.end !== undefined && params.end !== null) {
    query.set("end", String(params.end));
  }
  if (params.exclude_event_id !== undefined && params.exclude_event_id !== null) {
    query.set("exclude_event_id", String(params.exclude_event_id));
  }
  const suffix = query.toString();
  return appRequest<CheckConflictsResponse>("calendar", `/conflicts/check${suffix ? `?${suffix}` : ""}`);
}

export async function listEvents(params: ListEventsParams = {}): Promise<ListEventsResponse> {
  const query = new URLSearchParams();
  if (params.start !== undefined && params.start !== null) {
    query.set("start", String(params.start));
  }
  if (params.end !== undefined && params.end !== null) {
    query.set("end", String(params.end));
  }
  if (params.calendar_id !== undefined && params.calendar_id !== null) {
    query.set("calendar_id", String(params.calendar_id));
  }
  if (params.limit !== undefined && params.limit !== null) {
    query.set("limit", String(params.limit));
  }
  const suffix = query.toString();
  return appRequest<ListEventsResponse>("calendar", `/events${suffix ? `?${suffix}` : ""}`);
}

export async function createEvent(request: CreateEventRequest): Promise<EventRead> {
  return appRequest<EventRead>("calendar", `/events`, { method: "POST", body: request });
}

export async function searchEvents(params: SearchEventsParams): Promise<SearchEventsResponse> {
  const query = new URLSearchParams();
  if (params.q !== undefined && params.q !== null) {
    query.set("q", String(params.q));
  }
  if (params.limit !== undefined && params.limit !== null) {
    query.set("limit", String(params.limit));
  }
  const suffix = query.toString();
  return appRequest<SearchEventsResponse>("calendar", `/events/search${suffix ? `?${suffix}` : ""}`);
}

export async function deleteEvent(event_id: string): Promise<ActionResponse> {
  return appRequest<ActionResponse>("calendar", `/events/${encodeURIComponent(String(event_id))}`, { method: "DELETE" });
}

export async function getEvent(event_id: string): Promise<EventRead> {
  return appRequest<EventRead>("calendar", `/events/${encodeURIComponent(String(event_id))}`);
}

export async function updateEvent(event_id: string, request: UpdateEventRequest): Promise<EventRead> {
  return appRequest<EventRead>("calendar", `/events/${encodeURIComponent(String(event_id))}`, { method: "PATCH", body: request });
}

export async function createRecurringRule(event_id: string, request: CreateRecurringRuleRequest): Promise<RecurringRuleRead> {
  return appRequest<RecurringRuleRead>("calendar", `/events/${encodeURIComponent(String(event_id))}/recurring`, { method: "POST", body: request });
}

export async function getPreferences(): Promise<GetPreferencesResponse> {
  return appRequest<GetPreferencesResponse>("calendar", `/preferences`);
}

export async function updatePreferences(request: PreferenceUpdate[]): Promise<UpdatePreferencesResponse> {
  return appRequest<UpdatePreferencesResponse>("calendar", `/preferences`, { method: "PUT", body: request });
}

export async function listRecurringRules(): Promise<ListRecurringRulesResponse> {
  return appRequest<ListRecurringRulesResponse>("calendar", `/recurring`);
}

export async function stopRecurringRule(rule_id: string): Promise<RecurringRuleRead> {
  return appRequest<RecurringRuleRead>("calendar", `/recurring/${encodeURIComponent(String(rule_id))}/stop`, { method: "PATCH" });
}

export async function scheduleTask(task_id: string, request: ScheduleTaskRequest): Promise<EventRead> {
  return appRequest<EventRead>("calendar", `/tasks/${encodeURIComponent(String(task_id))}/schedule`, { method: "POST", body: request });
}

export async function listWidgets(): Promise<ListWidgetsResponse> {
  return appRequest<ListWidgetsResponse>("calendar", `/widgets`);
}
