/**
 * This file was auto-generated by scripts/codegen.py.
 * Do not make direct changes to the file.
 */

import { appRequest } from "@/api/apps";
import type {
  CalendarActionResponse,
  CalendarCalendarRead,
  CalendarCreateCalendarRequest,
  CalendarCreateEventRequest,
  CalendarCreateRecurringRuleRequest,
  CalendarEventRead,
  CalendarRecurringRuleRead,
  CalendarScheduleTaskRequest,
  CalendarUpdateCalendarRequest,
  CalendarUpdateEventRequest,
  ConfigFieldSchema,
  DaySummaryWidgetData,
  MonthViewWidgetData,
  PreferenceUpdate,
  UpcomingWidgetData,
  WidgetDataConfigSchema,
  WidgetDataConfigUpdate,
  WidgetManifestSchema,
  WidgetPreferenceSchema,
} from "@/types/generated";

export type ActionResponse = CalendarActionResponse;
export type CalendarRead = CalendarCalendarRead;
export type CreateCalendarRequest = CalendarCreateCalendarRequest;
export type CreateEventRequest = CalendarCreateEventRequest;
export type CreateRecurringRuleRequest = CalendarCreateRecurringRuleRequest;
export type EventRead = CalendarEventRead;
export type RecurringRuleRead = CalendarRecurringRuleRead;
export type ScheduleTaskRequest = CalendarScheduleTaskRequest;
export type UpdateCalendarRequest = CalendarUpdateCalendarRequest;
export type UpdateEventRequest = CalendarUpdateEventRequest;

export type RecurringFrequency = RecurringRuleRead["frequency"];

export type GetCalendarsResponse = CalendarRead[];
export type CheckConflictsResponse = EventRead[];
export type GetEventsResponse = EventRead[];
export type SearchEventsResponse = EventRead[];
export type GetPreferencesResponse = WidgetPreferenceSchema[];
export type UpdatePreferencesResponse = WidgetPreferenceSchema[];
export type GetRecurringRulesResponse = RecurringRuleRead[];
export type GetWidgetsResponse = WidgetManifestSchema[];
export type GetWidgetDataResponse = MonthViewWidgetData | UpcomingWidgetData | DaySummaryWidgetData;
export type GetWidgetOptionsResponse = ConfigFieldSchema[];

export interface CheckConflictsParams {
  start: string;
  end: string;
  exclude_event_id?: string | null;
}

export interface GetEventsParams {
  start?: string | null;
  end?: string | null;
  calendar_id?: string | null;
  limit?: number;
}

export interface SearchEventsParams {
  q: string;
  limit?: number;
}

export interface GetWidgetDataParams {
  month_offset?: number;
}

export async function getCalendars(): Promise<GetCalendarsResponse> {
  return appRequest<GetCalendarsResponse>("calendar", `/calendars`);
}

export async function createCalendar(request: CreateCalendarRequest): Promise<CalendarRead> {
  return appRequest<CalendarRead>("calendar", `/calendars`, { method: "POST", body: request });
}

export async function deleteCalendar(calendar_id: string): Promise<ActionResponse> {
  return appRequest<ActionResponse>("calendar", `/calendars/${encodeURIComponent(String(calendar_id))}`, { method: "DELETE" });
}

export async function updateCalendar(calendar_id: string, request: UpdateCalendarRequest): Promise<CalendarRead> {
  return appRequest<CalendarRead>("calendar", `/calendars/${encodeURIComponent(String(calendar_id))}`, { method: "PATCH", body: request });
}

export async function checkConflicts(params: CheckConflictsParams): Promise<CheckConflictsResponse> {
  const query = new URLSearchParams();
  if (params.start !== undefined && params.start !== null) {
    query.set("start", String(params.start));
  }
  if (params.end !== undefined && params.end !== null) {
    query.set("end", String(params.end));
  }
  if (params.exclude_event_id !== undefined && params.exclude_event_id !== null) {
    query.set("exclude_event_id", String(params.exclude_event_id));
  }
  const suffix = query.toString();
  return appRequest<CheckConflictsResponse>("calendar", `/conflicts/check${suffix ? `?${suffix}` : ""}`);
}

export async function getEvents(params: GetEventsParams = {}): Promise<GetEventsResponse> {
  const query = new URLSearchParams();
  if (params.start !== undefined && params.start !== null) {
    query.set("start", String(params.start));
  }
  if (params.end !== undefined && params.end !== null) {
    query.set("end", String(params.end));
  }
  if (params.calendar_id !== undefined && params.calendar_id !== null) {
    query.set("calendar_id", String(params.calendar_id));
  }
  if (params.limit !== undefined && params.limit !== null) {
    query.set("limit", String(params.limit));
  }
  const suffix = query.toString();
  return appRequest<GetEventsResponse>("calendar", `/events${suffix ? `?${suffix}` : ""}`);
}

export async function createEvent(request: CreateEventRequest): Promise<EventRead> {
  return appRequest<EventRead>("calendar", `/events`, { method: "POST", body: request });
}

export async function searchEvents(params: SearchEventsParams): Promise<SearchEventsResponse> {
  const query = new URLSearchParams();
  if (params.q !== undefined && params.q !== null) {
    query.set("q", String(params.q));
  }
  if (params.limit !== undefined && params.limit !== null) {
    query.set("limit", String(params.limit));
  }
  const suffix = query.toString();
  return appRequest<SearchEventsResponse>("calendar", `/events/search${suffix ? `?${suffix}` : ""}`);
}

export async function deleteEvent(event_id: string): Promise<ActionResponse> {
  return appRequest<ActionResponse>("calendar", `/events/${encodeURIComponent(String(event_id))}`, { method: "DELETE" });
}

export async function getEvent(event_id: string): Promise<EventRead> {
  return appRequest<EventRead>("calendar", `/events/${encodeURIComponent(String(event_id))}`);
}

export async function updateEvent(event_id: string, request: UpdateEventRequest): Promise<EventRead> {
  return appRequest<EventRead>("calendar", `/events/${encodeURIComponent(String(event_id))}`, { method: "PATCH", body: request });
}

export async function createRecurringRule(event_id: string, request: CreateRecurringRuleRequest): Promise<RecurringRuleRead> {
  return appRequest<RecurringRuleRead>("calendar", `/events/${encodeURIComponent(String(event_id))}/recurring`, { method: "POST", body: request });
}

export async function getPreferences(): Promise<GetPreferencesResponse> {
  return appRequest<GetPreferencesResponse>("calendar", `/preferences`);
}

export async function updatePreferences(request: PreferenceUpdate[]): Promise<UpdatePreferencesResponse> {
  return appRequest<UpdatePreferencesResponse>("calendar", `/preferences`, { method: "PUT", body: request });
}

export async function getRecurringRules(): Promise<GetRecurringRulesResponse> {
  return appRequest<GetRecurringRulesResponse>("calendar", `/recurring`);
}

export async function stopRecurringRule(rule_id: string): Promise<RecurringRuleRead> {
  return appRequest<RecurringRuleRead>("calendar", `/recurring/${encodeURIComponent(String(rule_id))}/stop`, { method: "PATCH" });
}

export async function scheduleTask(task_id: string, request: ScheduleTaskRequest): Promise<EventRead> {
  return appRequest<EventRead>("calendar", `/tasks/${encodeURIComponent(String(task_id))}/schedule`, { method: "POST", body: request });
}

export async function getWidgets(): Promise<GetWidgetsResponse> {
  return appRequest<GetWidgetsResponse>("calendar", `/widgets`);
}

export async function getWidgetData(widget_id: string, params: GetWidgetDataParams = {}): Promise<GetWidgetDataResponse> {
  const query = new URLSearchParams();
  if (params.month_offset !== undefined && params.month_offset !== null) {
    query.set("month_offset", String(params.month_offset));
  }
  const suffix = query.toString();
  return appRequest<GetWidgetDataResponse>("calendar", `/widgets/${encodeURIComponent(String(widget_id))}${suffix ? `?${suffix}` : ""}`);
}

export async function updateWidgetConfig(widget_id: string, request: WidgetDataConfigUpdate): Promise<WidgetDataConfigSchema> {
  return appRequest<WidgetDataConfigSchema>("calendar", `/widgets/${encodeURIComponent(String(widget_id))}/config`, { method: "PUT", body: request });
}

export async function getWidgetOptions(widget_id: string): Promise<GetWidgetOptionsResponse> {
  return appRequest<GetWidgetOptionsResponse>("calendar", `/widgets/${encodeURIComponent(String(widget_id))}/options`);
}
