/**
 * This file was auto-generated by scripts/codegen.py.
 * Do not make direct changes to the file.
 */

import type { ComponentType } from "react";

import { createDashboardWidgetRenderer } from "@/lib/dashboard-widget-renderer";

import type { DashboardWidgetRendererProps } from "./types";
import MonthViewWidget from "./widgets/MonthViewWidget";
import UpcomingWidget from "./widgets/UpcomingWidget";
import DaySummaryWidget from "./widgets/DaySummaryWidget";

const WIDGET_COMPONENTS = {
  "calendar.month-view": MonthViewWidget,
  "calendar.upcoming": UpcomingWidget,
  "calendar.day-summary": DaySummaryWidget,
} as const satisfies Record<string, ComponentType<DashboardWidgetRendererProps>>;

export default createDashboardWidgetRenderer(WIDGET_COMPONENTS);
