/**
 * This file was auto-generated by scripts/codegen.py.
 * Do not make direct changes to the file.
 */

// Core API routes generated from backend OpenAPI.

export const AUTH_ROUTES = {
  LOGIN: "/auth/login",
  LOGOUT: "/auth/logout",
  ME: "/auth/me",
  ME_AVATAR: "/auth/me/avatar",
  SETTINGS: "/auth/me/settings",
  REFRESH: "/auth/refresh",
  REGISTER: "/auth/register",
} as const;

export const API_PATHS = {
  ADMIN_APPS: "/api/admin/apps",
  ADMIN_APP_TIER: (appId: string | number) => `/api/admin/apps/${encodeURIComponent(String(appId))}/tier`,
  ADMIN_STATS: "/api/admin/stats",
  ADMIN_SUBSCRIPTIONS: "/api/admin/subscriptions",
  ADMIN_SUBSCRIPTION_USER: (userId: string | number) => `/api/admin/subscriptions/${encodeURIComponent(String(userId))}`,
  ADMIN_USERS: "/api/admin/users",
  ADMIN_USER_ROLE: (userId: string | number) => `/api/admin/users/${encodeURIComponent(String(userId))}/role`,
  LOGIN: "/api/auth/login",
  LOGOUT: "/api/auth/logout",
  ME: "/api/auth/me",
  ME_AVATAR: "/api/auth/me/avatar",
  SETTINGS: "/api/auth/me/settings",
  REFRESH: "/api/auth/refresh",
  REGISTER: "/api/auth/register",
  CATALOG_APPS: "/api/catalog",
  CATALOG_CATEGORIES: "/api/catalog/categories",
  CATALOG_CATEGORY: (categoryId: string | number) => `/api/catalog/categories/${encodeURIComponent(String(categoryId))}`,
  CATALOG_INSTALL: "/api/catalog/install",
  CATALOG_ALL_PREFERENCES: "/api/catalog/preferences",
  CATALOG_PREFERENCES: (appId: string | number) => `/api/catalog/preferences/${encodeURIComponent(String(appId))}`,
  CATALOG_UNINSTALL: "/api/catalog/uninstall",
  CHAT_STREAM: "/api/chat/stream",
  SUBSCRIPTION_CANCEL: "/api/subscription/cancel",
  SUBSCRIPTION_CHECKOUT: "/api/subscription/checkout",
  SUBSCRIPTION_ME: "/api/subscription/subscription",
  SUBSCRIPTION_WEBHOOK_PAYOS: "/api/subscription/webhook/payos",
  SUBSCRIPTION_WEBHOOK_STRIPE: "/api/subscription/webhook/stripe",
  WORKSPACE_BOOTSTRAP: "/api/workspace/bootstrap",
} as const;
