/**
 * This file was auto-generated by scripts/codegen.py.
 * Do not make direct changes to the file.
 */

import { appRequest } from "@/api/apps";
import type {
  PreferenceUpdate,
  TodoActionResponse,
  TodoCreateRecurringRuleRequest,
  TodoCreateSubTaskRequest,
  TodoCreateTaskRequest,
  TodoRecurringRuleRead,
  TodoSubTaskRead,
  TodoSummaryResponse,
  TodoTaskDetailRead,
  TodoTaskRead,
  TodoUpdateTaskRequest,
  WidgetManifestSchema,
  WidgetPreferenceSchema,
} from "@/types/generated";

export type ActionResponse = TodoActionResponse;
export type CreateRecurringRuleRequest = TodoCreateRecurringRuleRequest;
export type CreateSubTaskRequest = TodoCreateSubTaskRequest;
export type CreateTaskRequest = TodoCreateTaskRequest;
export type RecurringRuleRead = TodoRecurringRuleRead;
export type SubTaskRead = TodoSubTaskRead;
export type SummaryResponse = TodoSummaryResponse;
export type TaskDetailRead = TodoTaskDetailRead;
export type TaskRead = TodoTaskRead;
export type UpdateTaskRequest = TodoUpdateTaskRequest;

export type RecurringFrequency = RecurringRuleRead["frequency"];

export type GetPreferencesResponse = WidgetPreferenceSchema[];
export type UpdatePreferencesResponse = WidgetPreferenceSchema[];
export type GetRecurringRulesResponse = RecurringRuleRead[];
export type GetTasksResponse = TaskRead[];
export type GetArchivedTasksResponse = TaskRead[];
export type SearchTasksResponse = TaskRead[];
export type GetSubtasksResponse = SubTaskRead[];
export type ListWidgetsResponse = WidgetManifestSchema[];

export interface GetTasksParams {
  status?: "pending" | "completed" | null;
  priority?: "low" | "medium" | "high" | null;
  tag?: string | null;
  limit?: number;
}

export interface GetArchivedTasksParams {
  limit?: number;
}

export interface SearchTasksParams {
  q: string;
  include_archived?: boolean;
  limit?: number;
}

export async function getPreferences(): Promise<GetPreferencesResponse> {
  return appRequest<GetPreferencesResponse>("todo", `/preferences`);
}

export async function updatePreferences(request: PreferenceUpdate[]): Promise<UpdatePreferencesResponse> {
  return appRequest<UpdatePreferencesResponse>("todo", `/preferences`, { method: "PUT", body: request });
}

export async function getRecurringRules(): Promise<GetRecurringRulesResponse> {
  return appRequest<GetRecurringRulesResponse>("todo", `/recurring`);
}

export async function stopRecurringRule(rule_id: string): Promise<RecurringRuleRead> {
  return appRequest<RecurringRuleRead>("todo", `/recurring/${encodeURIComponent(String(rule_id))}/stop`, { method: "PATCH" });
}

export async function deleteSubtask(subtask_id: string): Promise<ActionResponse> {
  return appRequest<ActionResponse>("todo", `/subtasks/${encodeURIComponent(String(subtask_id))}`, { method: "DELETE" });
}

export async function completeSubtask(subtask_id: string): Promise<SubTaskRead> {
  return appRequest<SubTaskRead>("todo", `/subtasks/${encodeURIComponent(String(subtask_id))}/complete`, { method: "PATCH" });
}

export async function uncompleteSubtask(subtask_id: string): Promise<SubTaskRead> {
  return appRequest<SubTaskRead>("todo", `/subtasks/${encodeURIComponent(String(subtask_id))}/uncomplete`, { method: "PATCH" });
}

export async function getTodoSummary(): Promise<SummaryResponse> {
  return appRequest<SummaryResponse>("todo", `/summary`);
}

export async function getTasks(params: GetTasksParams = {}): Promise<GetTasksResponse> {
  const query = new URLSearchParams();
  if (params.status !== undefined && params.status !== null) {
    query.set("status", String(params.status));
  }
  if (params.priority !== undefined && params.priority !== null) {
    query.set("priority", String(params.priority));
  }
  if (params.tag !== undefined && params.tag !== null) {
    query.set("tag", String(params.tag));
  }
  if (params.limit !== undefined && params.limit !== null) {
    query.set("limit", String(params.limit));
  }
  const suffix = query.toString();
  return appRequest<GetTasksResponse>("todo", `/tasks${suffix ? `?${suffix}` : ""}`);
}

export async function createTask(request: CreateTaskRequest): Promise<TaskRead> {
  return appRequest<TaskRead>("todo", `/tasks`, { method: "POST", body: request });
}

export async function getArchivedTasks(params: GetArchivedTasksParams = {}): Promise<GetArchivedTasksResponse> {
  const query = new URLSearchParams();
  if (params.limit !== undefined && params.limit !== null) {
    query.set("limit", String(params.limit));
  }
  const suffix = query.toString();
  return appRequest<GetArchivedTasksResponse>("todo", `/tasks/archived/list${suffix ? `?${suffix}` : ""}`);
}

export async function searchTasks(params: SearchTasksParams): Promise<SearchTasksResponse> {
  const query = new URLSearchParams();
  if (params.q !== undefined && params.q !== null) {
    query.set("q", String(params.q));
  }
  if (params.include_archived !== undefined && params.include_archived !== null) {
    query.set("include_archived", String(params.include_archived));
  }
  if (params.limit !== undefined && params.limit !== null) {
    query.set("limit", String(params.limit));
  }
  const suffix = query.toString();
  return appRequest<SearchTasksResponse>("todo", `/tasks/search${suffix ? `?${suffix}` : ""}`);
}

export async function deleteTask(task_id: string): Promise<ActionResponse> {
  return appRequest<ActionResponse>("todo", `/tasks/${encodeURIComponent(String(task_id))}`, { method: "DELETE" });
}

export async function getTask(task_id: string): Promise<TaskDetailRead> {
  return appRequest<TaskDetailRead>("todo", `/tasks/${encodeURIComponent(String(task_id))}`);
}

export async function updateTask(task_id: string, request: UpdateTaskRequest): Promise<TaskRead> {
  return appRequest<TaskRead>("todo", `/tasks/${encodeURIComponent(String(task_id))}`, { method: "PATCH", body: request });
}

export async function archiveTask(task_id: string): Promise<TaskRead> {
  return appRequest<TaskRead>("todo", `/tasks/${encodeURIComponent(String(task_id))}/archive`, { method: "PATCH" });
}

export async function createRecurringRule(task_id: string, request: CreateRecurringRuleRequest): Promise<RecurringRuleRead> {
  return appRequest<RecurringRuleRead>("todo", `/tasks/${encodeURIComponent(String(task_id))}/recurring`, { method: "POST", body: request });
}

export async function restoreTask(task_id: string): Promise<TaskRead> {
  return appRequest<TaskRead>("todo", `/tasks/${encodeURIComponent(String(task_id))}/restore`, { method: "PATCH" });
}

export async function getSubtasks(task_id: string): Promise<GetSubtasksResponse> {
  return appRequest<GetSubtasksResponse>("todo", `/tasks/${encodeURIComponent(String(task_id))}/subtasks`);
}

export async function createSubtask(task_id: string, request: CreateSubTaskRequest): Promise<SubTaskRead> {
  return appRequest<SubTaskRead>("todo", `/tasks/${encodeURIComponent(String(task_id))}/subtasks`, { method: "POST", body: request });
}

export async function removeTag(task_id: string, tag: string): Promise<TaskRead> {
  return appRequest<TaskRead>("todo", `/tasks/${encodeURIComponent(String(task_id))}/tags/${encodeURIComponent(String(tag))}`, { method: "DELETE" });
}

export async function addTag(task_id: string, tag: string): Promise<TaskRead> {
  return appRequest<TaskRead>("todo", `/tasks/${encodeURIComponent(String(task_id))}/tags/${encodeURIComponent(String(tag))}`, { method: "POST" });
}

export async function toggleTask(task_id: string): Promise<TaskRead> {
  return appRequest<TaskRead>("todo", `/tasks/${encodeURIComponent(String(task_id))}/toggle`, { method: "PATCH" });
}

export async function listWidgets(): Promise<ListWidgetsResponse> {
  return appRequest<ListWidgetsResponse>("todo", `/widgets`);
}
