/**
 * This file was auto-generated by scripts/codegen.py.
 * Do not make direct changes to the file.
 */

import type { ComponentType } from "react";

import { createDashboardWidgetRenderer } from "@/lib/dashboard-widget-renderer";

import type { DashboardWidgetRendererProps } from "./types";
import TaskListWidget from "./widgets/TaskListWidget";
import TodayWidget from "./widgets/TodayWidget";

const WIDGET_COMPONENTS = {
  "todo.task-list": TaskListWidget,
  "todo.today": TodayWidget,
} as const satisfies Record<string, ComponentType<DashboardWidgetRendererProps>>;

export default createDashboardWidgetRenderer(WIDGET_COMPONENTS);
