#!/usr/bin/env python3
"""
Codegen — generates TypeScript types and app-local API clients from the backend OpenAPI spec.

Pipeline:
  FastAPI app -> openapi.json -> openapi-typescript -> generated schema types/barrel
  OpenAPI app routes -> frontend/src/apps/{app}/api.ts

Environment (for generating openapi.json):
    Requires conda environment `linhdz` to be active, OR set these env vars:
    MONGODB_URI, JWT_SECRET, OPENAI_API_KEY, OPENAI_BASE_URL

Usage:
    # With conda activated:
    conda run -n linhdz python scripts/codegen.py

    # Or from any shell (reads .env automatically):
    python scripts/codegen.py
"""

import json
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BACKEND_DIR = ROOT / "backend"
OPENAPI_SPEC = ROOT / "openapi.json"
OUTPUT = ROOT / "frontend" / "src" / "types" / "generated" / "api.ts"
INDEX_OUTPUT = ROOT / "frontend" / "src" / "types" / "generated" / "index.ts"
FRONTEND_APPS_DIR = ROOT / "frontend" / "src" / "apps"
FUNCTION_NAME_OVERRIDES = {
    "calendar": {
        "create_recurring": "createRecurringRule",
        "list_recurring_rules": "listRecurringRules",
        "stop_recurring": "stopRecurringRule",
    },
    "finance": {
        "finance_summary": "getFinanceSummary",
        "get_category_breakdown": "getCategoryBreakdown",
        "get_monthly_trend": "getMonthlyTrend",
        "list_categories": "getCategories",
        "list_transactions": "getTransactions",
        "list_wallets": "getWallets",
        "transfer_funds": "transfer",
    },
    "todo": {
        "add_subtask": "createSubtask",
        "get_subtasks": "getSubtasks",
        "list_archived": "getArchivedTasks",
        "list_recurring_rules": "getRecurringRules",
        "list_tasks": "getTasks",
        "todo_summary": "getTodoSummary",
    },
}
DERIVED_TYPE_ALIASES = {
    "todo": {
        "RecurringFrequency": 'RecurringRuleRead["frequency"]',
    },
}

# Backend env defaults — can override via environment variables
_backend_env = {
    "MONGODB_URI": "mongodb+srv://nhatquangpx:8sotamnhe@gymmanagement.8jghrjf.mongodb.net/?retryWrites=true&w=majority",
    "JWT_SECRET": "shin-superin-dev-secret",
    "OPENAI_API_KEY": "fw_HToZECoeccNqkpq69XUi1a",
    "OPENAI_BASE_URL": "https://api.fireworks.ai/inference/v1",
}


def _run_python(cmd: str) -> subprocess.CompletedProcess:
    """Run Python snippet in linhdz environment."""
    env = {**os.environ, **{k: v for k, v in _backend_env.items() if v}}

    # Use absolute path to linhdz python to avoid conda run nesting issues.
    # /home/linh/miniconda3/envs/linhdz/bin/python3 is always correct
    # regardless of which conda env the outer process is in.
    python_bin = "/home/linh/miniconda3/envs/linhdz/bin/python3"

    result = subprocess.run(
        [python_bin, "-c", cmd],
        cwd=str(ROOT),
        capture_output=True,
        text=True,
        env=env,
    )
    return result


def generate_openapi_spec() -> None:
    """Build openapi.json by importing the FastAPI app."""
    backend_path = str(BACKEND_DIR.resolve())
    script = (
        f"import sys\n"
        f"sys.path.insert(0, {backend_path!r})\n"
        "from core.main import app\n"
        "import json\n"
        "spec = app.openapi()\n"
        f"with open({str(OPENAPI_SPEC)!r}, 'w') as f:\n"
        "    json.dump(spec, f, indent=2)\n"
        "print('paths:', len(spec.get('paths', {})), 'schemas:', len(spec.get('components', {}).get('schemas', {})))\n"
    )

    result = _run_python(script)
    if result.returncode != 0:
        print("[codegen] ERROR generating OpenAPI spec:")
        print(result.stderr[-2000:])
        sys.exit(1)
    print("[codegen] ✓ " + result.stdout.strip())


def run_typescript_codegen() -> None:
    """Run openapi-typescript to generate TypeScript interfaces."""
    result = subprocess.run(
        ["openapi-typescript", str(OPENAPI_SPEC), "-o", str(OUTPUT)],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print("[codegen] ERROR running openapi-typescript:")
        print(result.stderr[-2000:])
        sys.exit(1)
    print("[codegen] ✓ Types generated ->", OUTPUT)


def generate_typescript_index() -> None:
    """Generate a stable barrel file that re-exports all schema aliases."""
    spec = json.loads(OPENAPI_SPEC.read_text())
    schemas = spec.get("components", {}).get("schemas", {})

    lines = [
        "/**",
        " * This file was auto-generated by scripts/codegen.py.",
        " * Do not make direct changes to the file.",
        " */",
        "",
        'import type { components, operations, paths } from "./api";',
        "",
        'export type { components, operations, paths } from "./api";',
        "",
        'export type Schemas = components["schemas"];',
        'export type SchemaName = keyof Schemas;',
        "",
    ]

    valid_identifier = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
    for schema_name in sorted(schemas):
        if not valid_identifier.match(schema_name):
            continue
        lines.append(f'export type {schema_name} = Schemas["{schema_name}"];')

    lines.extend(
        [
            "",
            "export type OperationMap = operations;",
            "export type PathMap = paths;",
            "",
        ]
    )

    INDEX_OUTPUT.write_text("\n".join(lines))
    print("[codegen] ✓ Barrel generated ->", INDEX_OUTPUT)


def load_plugin_manifests() -> dict[str, dict]:
    """Load registered backend plugin manifests as plain JSON-compatible dicts."""
    backend_path = str(BACKEND_DIR.resolve())
    script = f"""
import sys
sys.path.insert(0, {backend_path!r})
import json
from core.discovery import discover_apps

discover_apps()

from core.registry import PLUGIN_REGISTRY

payload = {{
    app_id: entry["manifest"].model_dump(mode="json")
    for app_id, entry in sorted(PLUGIN_REGISTRY.items())
}}
print(json.dumps(payload))
"""

    result = _run_python(script)
    if result.returncode != 0:
        print("[codegen] ERROR loading plugin manifests:")
        print(result.stderr[-2000:])
        sys.exit(1)

    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError:
        print("[codegen] ERROR parsing plugin manifests JSON:")
        print(result.stdout[-2000:])
        sys.exit(1)


def get_app_ids(paths: dict) -> list[str]:
    app_ids = {
        match.group(1)
        for path in paths
        if (match := re.match(r"^/api/apps/([^/]+)/", path))
    }
    return sorted(app_ids)


def get_app_api_output(app_id: str) -> Path:
    return FRONTEND_APPS_DIR / app_id / "api.ts"


def get_app_dashboard_output(app_id: str) -> Path:
    return FRONTEND_APPS_DIR / app_id / "DashboardWidget.tsx"


def to_pascal_case(value: str) -> str:
    parts = [part for part in re.split(r"[_\-]+", value) if part]
    return "".join(part[:1].upper() + part[1:] for part in parts)


def to_camel_case(value: str) -> str:
    pascal = to_pascal_case(value)
    if not pascal:
        return value
    return pascal[:1].lower() + pascal[1:]


def unique_preserve_order(values: list[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        result.append(value)
    return result


def get_ref_name(schema: dict | None) -> str | None:
    if not schema:
        return None
    ref = schema.get("$ref")
    if not ref:
        return None
    return ref.rsplit("/", 1)[-1]


def collect_schema_refs(schema: dict | None) -> set[str]:
    refs: set[str] = set()
    if not schema:
        return refs

    ref_name = get_ref_name(schema)
    if ref_name:
        refs.add(ref_name)

    for key in ("anyOf", "oneOf", "allOf"):
        for item in schema.get(key, []):
            refs.update(collect_schema_refs(item))

    if schema.get("type") == "array":
        refs.update(collect_schema_refs(schema.get("items")))

    if schema.get("type") == "object":
        for prop in schema.get("properties", {}).values():
            refs.update(collect_schema_refs(prop))
        refs.update(collect_schema_refs(schema.get("additionalProperties")))

    return refs


def app_local_schema_name(app_id: str, schema_name: str) -> str:
    prefix = to_pascal_case(app_id)
    if schema_name.startswith(prefix):
        return schema_name[len(prefix):]
    return schema_name


def ts_type_from_schema(app_id: str, schema: dict | None) -> str:
    if not schema:
        return "unknown"

    ref_name = get_ref_name(schema)
    if ref_name:
        return app_local_schema_name(app_id, ref_name)

    for key in ("anyOf", "oneOf", "allOf"):
        options = schema.get(key)
        if options:
            return " | ".join(unique_preserve_order([ts_type_from_schema(app_id, option) for option in options]))

    schema_type = schema.get("type")
    if schema_type == "array":
        return f'{ts_type_from_schema(app_id, schema.get("items"))}[]'
    if schema_type == "integer" or schema_type == "number":
        return "number"
    if schema_type == "string":
        values = schema.get("enum")
        if values:
            return " | ".join(json.dumps(value) for value in values)
        return "string"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "object":
        additional = schema.get("additionalProperties")
        if additional is not None:
            return f'Record<string, {ts_type_from_schema(app_id, additional)}>'
        return "Record<string, unknown>"

    return "unknown"


def get_success_response_schema(operation: dict) -> dict | None:
    responses = operation.get("responses", {})
    for status in sorted(responses.keys()):
        if not str(status).startswith("2"):
            continue
        return responses[status].get("content", {}).get("application/json", {}).get("schema")
    return None


def get_request_body_schema(operation: dict) -> dict | None:
    return (
        operation.get("requestBody", {})
        .get("content", {})
        .get("application/json", {})
        .get("schema")
    )


def get_operation_prefix(operation_id: str, app_id: str) -> str:
    marker = f"_api_apps_{app_id}_"
    if marker not in operation_id:
        return operation_id
    return operation_id.split(marker, 1)[0]


def get_function_name(app_id: str, method: str, operation_id: str) -> str:
    prefix = get_operation_prefix(operation_id, app_id)
    override = FUNCTION_NAME_OVERRIDES.get(app_id, {}).get(prefix)
    if override:
        return override

    if method == "get" and not prefix.startswith(("get_", "list_", "search_", "check_")):
        prefix = f"get_{prefix}"

    return to_camel_case(prefix)


def render_interface(name: str, properties: list[dict]) -> list[str]:
    lines = [f"export interface {name} {{"]
    for prop in properties:
        optional = "?" if not prop["required"] else ""
        lines.append(f'  {prop["name"]}{optional}: {prop["ts_type"]};')
    lines.append("}")
    return lines


def render_query_builder(properties: list[dict]) -> list[str]:
    lines = ["  const query = new URLSearchParams();"]
    for prop in properties:
        access = f'params.{prop["name"]}'
        if prop["is_array"]:
            lines.append(f"  if ({access}) {{")
            lines.append(f"    for (const value of {access}) {{")
            lines.append(f'      query.append("{prop["wire_name"]}", String(value));')
            lines.append("    }")
            lines.append("  }")
            continue

        lines.append(f"  if ({access} !== undefined && {access} !== null) {{")
        lines.append(f'    query.set("{prop["wire_name"]}", String({access}));')
        lines.append("  }")
    lines.append('  const suffix = query.toString();')
    return lines


def generate_app_api_clients(app_ids: list[str]) -> None:
    spec = json.loads(OPENAPI_SPEC.read_text())
    schemas = spec.get("components", {}).get("schemas", {})
    paths = spec.get("paths", {})

    for app_id in app_ids:
        output_path = get_app_api_output(app_id)
        app_operations: list[tuple[str, str, dict]] = []
        used_refs: set[str] = set()

        for path, methods in sorted(paths.items()):
            if not path.startswith(f"/api/apps/{app_id}/"):
                continue

            for method, operation in sorted(methods.items()):
                app_operations.append((path, method, operation))
                for parameter in operation.get("parameters", []):
                    used_refs.update(collect_schema_refs(parameter.get("schema")))
                used_refs.update(collect_schema_refs(get_request_body_schema(operation)))
                used_refs.update(collect_schema_refs(get_success_response_schema(operation)))

        imported_types = sorted(ref for ref in used_refs if ref in schemas)
        app_schema_aliases = sorted(
            schema_name
            for schema_name in imported_types
            if schema_name.startswith(to_pascal_case(app_id))
        )

        lines = [
            "/**",
            " * This file was auto-generated by scripts/codegen.py.",
            " * Do not make direct changes to the file.",
            " */",
            "",
            'import { appRequest } from "@/api/apps";',
        ]

        if imported_types:
            lines.extend(
                [
                    'import type {',
                    *[f"  {type_name}," for type_name in imported_types],
                    '} from "@/types/generated";',
                ]
            )

        lines.append("")

        for schema_name in app_schema_aliases:
            lines.append(
                f"export type {app_local_schema_name(app_id, schema_name)} = {schema_name};"
            )

        derived_aliases = DERIVED_TYPE_ALIASES.get(app_id, {})
        if derived_aliases:
            if app_schema_aliases:
                lines.append("")
            for alias_name, target in derived_aliases.items():
                lines.append(f"export type {alias_name} = {target};")

        response_alias_lines: list[str] = []
        interface_lines: list[str] = []
        function_lines: list[str] = []

        for path, method, operation in app_operations:
            operation_id = operation["operationId"]
            function_name = get_function_name(app_id, method, operation_id)
            function_pascal = to_pascal_case(function_name)

            path_parameters = []
            query_parameters = []
            for parameter in operation.get("parameters", []):
                schema = parameter.get("schema", {})
                info = {
                    "name": parameter["name"],
                    "wire_name": parameter["name"],
                    "required": parameter.get("required", False),
                    "ts_type": ts_type_from_schema(app_id, schema),
                    "is_array": schema.get("type") == "array",
                }
                if parameter.get("in") == "path":
                    path_parameters.append(info)
                elif parameter.get("in") == "query":
                    query_parameters.append(info)

            request_schema = get_request_body_schema(operation)
            request_type = ts_type_from_schema(app_id, request_schema) if request_schema else None
            response_schema = get_success_response_schema(operation)
            response_type = ts_type_from_schema(app_id, response_schema)
            response_ref = get_ref_name(response_schema)

            if response_ref is None and response_schema is not None:
                response_alias_name = f"{function_pascal}Response"
                response_alias_lines.append(
                    f"export type {response_alias_name} = {response_type};"
                )
                response_type = response_alias_name

            query_type_name = None
            if query_parameters:
                query_type_name = f"{function_pascal}Params"
                interface_lines.extend(render_interface(query_type_name, query_parameters))
                interface_lines.append("")

            function_signature: list[str] = []
            for parameter in path_parameters:
                function_signature.append(f'{parameter["name"]}: {parameter["ts_type"]}')
            if request_type:
                function_signature.append(f"request: {request_type}")
            if query_type_name:
                has_required_query = any(prop["required"] for prop in query_parameters)
                default_value = "" if has_required_query else " = {}"
                function_signature.append(f"params: {query_type_name}{default_value}")

            path_template = path.replace(f"/api/apps/{app_id}", "")
            for parameter in path_parameters:
                replacement = "${encodeURIComponent(String(" + parameter["name"] + "))}"
                path_template = path_template.replace("{" + parameter["wire_name"] + "}", replacement)

            function_lines.append(
                f'export async function {function_name}({", ".join(function_signature)}): Promise<{response_type}> {{'
            )
            if query_parameters:
                function_lines.extend(render_query_builder(query_parameters))
                target_path = f'`{path_template}${{suffix ? `?${{suffix}}` : ""}}`'
            else:
                target_path = f'`{path_template}`'

            if method == "get":
                function_lines.append(
                    f'  return appRequest<{response_type}>("{app_id}", {target_path});'
                )
            else:
                request_init_parts = [f'method: "{method.upper()}"']
                if request_type:
                    request_init_parts.append("body: request")
                function_lines.append(
                    f'  return appRequest<{response_type}>("{app_id}", {target_path}, {{ {", ".join(request_init_parts)} }});'
                )
            function_lines.append("}")
            function_lines.append("")

        if app_schema_aliases or derived_aliases:
            lines.append("")
        if response_alias_lines:
            lines.extend(response_alias_lines)
            lines.append("")
        if interface_lines:
            lines.extend(interface_lines)
        lines.extend(function_lines)

        content = "\n".join(lines).rstrip() + "\n"
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content)
        print("[codegen] ✓ App API generated ->", output_path)


def widget_component_name(widget_id: str) -> str:
    _, _, widget_slug = widget_id.partition(".")
    return f"{to_pascal_case(widget_slug)}Widget"


def generate_app_dashboard_renderers(manifests: dict[str, dict]) -> None:
    for app_id, manifest in sorted(manifests.items()):
        widgets = manifest.get("widgets", [])
        output_path = get_app_dashboard_output(app_id)
        lines = [
            "/**",
            " * This file was auto-generated by scripts/codegen.py.",
            " * Do not make direct changes to the file.",
            " */",
            "",
            'import type { ComponentType } from "react";',
            "",
            'import { createDashboardWidgetRenderer } from "@/lib/dashboard-widget-renderer";',
            "",
            'import type { DashboardWidgetRendererProps } from "./types";',
        ]

        for widget in widgets:
            component_name = widget_component_name(widget["id"])
            lines.append(f'import {component_name} from "./widgets/{component_name}";')

        lines.extend(["", "const WIDGET_COMPONENTS = {"])
        for widget in widgets:
            component_name = widget_component_name(widget["id"])
            lines.append(f'  "{widget["id"]}": {component_name},')
        lines.extend(
            [
                '} as const satisfies Record<string, ComponentType<DashboardWidgetRendererProps>>;',
                "",
                "export default createDashboardWidgetRenderer(WIDGET_COMPONENTS);",
                "",
            ]
        )

        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text("\n".join(lines))
        print("[codegen] ✓ App dashboard generated ->", output_path)


def main() -> None:
    print("[codegen] Step 1: Generating OpenAPI spec from FastAPI app...")
    generate_openapi_spec()

    print("[codegen] Step 2: Generating TypeScript types from OpenAPI spec...")
    run_typescript_codegen()
    generate_typescript_index()

    manifests = load_plugin_manifests()
    app_ids = get_app_ids(json.loads(OPENAPI_SPEC.read_text()).get("paths", {}))

    print("[codegen] Step 3: Generating app-local API clients...")
    generate_app_api_clients(app_ids)

    print("[codegen] Step 4: Generating app-local dashboard renderers...")
    generate_app_dashboard_renderers(manifests)

    print("[codegen] ✓ Done — import contracts from generated app/api or '@/types/generated'")


if __name__ == "__main__":
    main()
